package com.kotlin.app_config_plugin

object Version {
    const val androidXCore = "1.8.0"
    const val appcompat = "1.4.1"
    const val junit = "4.13.2"
    const val junitTestExt = "1.1.3"
    const val espresso = "3.4.0"
    const val material = "1.5.0"
    const val koinVersion = "3.4.2"
    const val retrofit = "2.9.0"
    const val okHttp = "4.1.0"
    const val androidktxCore= "1.9.0"
    const val kotlinVersion = "1.8.10"
    const val compose = "1.4.2"
    const val composeConstraintLayout = "1.0.1"
    const val kotlinCompilerVersion = "1.6.21"
    const val composeActivity = "1.7.1"

    const val activity      = "1.5.1"
    const val ktor          = "2.3.2"
    const val serialization = "1.4.1"
    const val koin          = "3.3.2"
    const val koinCompose   = "3.4.1"
    const val coil          = "1.3.1"
    const val lifecycle     = "2.5.1"
    const val navigation    = "2.5.3"
    const val material3     = "1.0.1"
    const val kermit        = "1.2.2"
    const val mockk         = "1.13.3"
    const val mockkCommon   = "1.12.5"
    const val turbine       = "0.12.1"
    const val coroutines    = "1.6.4"
    const val supabase      = "1.2.0"
    const val buildkonfig   = "0.13.3"
    const val kswift        = "0.6.1"
    const val mokoResourcesGenerator = "0.23.0"
    const val mokoGraphics = "0.9.0"
    const val mokoPermissions = "0.16.0"
    const val mokoMvvmVersion = "0.16.1"
    const val mokoGeo = "0.6.0"
    const val mokoMedia = "0.11.0"
    const val mokoMediaFilePicker = "1.9.1"
}